name: TactileText
options:
  createIntermediateGroups: true
targets:
  TactileText:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        includes:
          - "*.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tianchenhao.TactileText
        PRODUCT_NAME: TactileText
        SWIFT_VERSION: 6.0
        TARGETED_DEVICE_FAMILY: "1,2"
        DEVELOPMENT_ASSET_PATHS: "\"\""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    scheme:
      testTargets: []
